# Rust formatting configuration for rCandle
# Using only stable features for CI compatibility
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true

# Unstable features (require nightly):
# Uncomment these if using nightly toolchain locally
# format_code_in_doc_comments = true
# normalize_comments = true
# wrap_comments = true
# comment_width = 80
# format_strings = true
# format_macro_matchers = true
# format_macro_bodies = true
# imports_granularity = "Crate"
# group_imports = "StdExternalCrate"
