# Cargo configuration for rCandle

[build]
# Increase parallel jobs for faster builds
jobs = 4

# Use all available cores for codegen
# codegen-units = 16  # Uncomment for faster debug builds (slower runtime)

[target.x86_64-unknown-linux-gnu]
# Use lld linker for faster linking on Linux (if available)
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-pc-windows-msvc]
# Windows-specific optimizations
# rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-apple-darwin]
# macOS-specific optimizations

[alias]
# Useful cargo aliases
check-all = "check --all-targets --all-features"
test-all = "test --all-targets --all-features"
build-release = "build --release"
run-release = "run --release"

[profile.dev]
# Debug profile with faster builds
opt-level = 0
debug = true
split-debuginfo = "unpacked"

[profile.release]
# Release profile with maximum optimization
opt-level = 3
lto = true
codegen-units = 1
strip = true
